### ISSUE TITLE
if (i > mesh->m_pEdge[i].m_iTwinEdge) continue;

### ISSUE THREAD

**Issue by petrasvestartas** [Narusaki/LBO#1]
What does this line mean?

if (i > mesh->m_pEdge[i].m_iTwinEdge) continue;

In the loop like this?

	for (unsigned i = 0; i < mesh->m_nEdge; ++i){

             if (i > mesh->m_pEdge[i].m_iTwinEdge) continue;

        }

**Comment by Narusaki** [comment]
Since I'm using a half-edge structure, each physical edge (except for boundaries) is composed of a pair of "twin edges", which is indexed in [0, mesh->m_nEdge-1]. A loop you mentioned means that only one of the twin edges is considered for each physical edge.

**Comment by lzcchl** [comment]
你的代码有bug，因为m_iTwinEdge是UINT，但是却初始化为-1，这就导致这个判断没有按你的逻辑走下去，改成if ((int)i > (int)mesh->m_pEdge[i].m_iTwinEdge) continue;来暂时性的解决这个问题。
